---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    name: go-rest-api